#pragma once

#define QUADTREE_MAX_OBJECTS 4
#define QUADTREE_MAX_LEVELS 8
#define DEFAULT_IMPULSE_MULTIPLIER 1
#define IMPULSE_MULTIPLIER DEFAULT_IMPULSE_MULTIPLIER
#define PHYSICS_EPSILON 0.000009f
#define GL_DRAW_CIRCLE_TRIANGLE_AMOUNT 20
#define COLLISION_FLASH_DURATION 5
#define SIMULATION_TIMESCALE 10.0 * 2.0
//#define SIMULATION_LOSSES
#define SIMULATION_GRAVITY 0.0
#define USE_QUADTREES
