#pragma once

#define QUADTREE_MAX_OBJECTS 4
#define QUADTREE_MAX_LEVELS 10
#define DEFAULT_IMPULSE_MULTIPLIER 1
#define IMPULSE_MULTIPLIER DEFAULT_IMPULSE_MULTIPLIER
#define PHYSICS_EPSILON 0.000009f
#define GL_DRAW_CIRCLE_TRIANGLE_AMOUNT 20
